version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - bix
networks:
  bix:
    driver: bridge
    name: bix
